# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "..", "/vagrant", type: "nfs", nfs_export: false

  config.vm.define "vmware-test" do |test|
    test.vm.box = "yogendra/boot2docker-vmware"
    test.vm.box_url = "file://"+ File.dirname(File.expand_path('..', __FILE__)) +"/boot2docker-vmware.box"

    ["vmware_fusion", "vmware_workstation"].each do |vmware|
      test.vm.provider vmware do |provider|
        provider.vmx['memsize'] = 2096
        provider.vmx['numvcpus'] = 2
      end
    end
  end
end
